### ISSUE TITLE
GET and POST require too many auth parameters

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/plugin-servicenow#33]
### Expected Behavior

If you're using basic auth you do not need clientID and clientSecret. Likewise, if you're using clientID and secret you do not need username and password. 

### Actual Behaviour

Kestra requires all 4 parameters

### Steps To Reproduce

using servicenow dev account
```   
  - id: http
    type: io.kestra.plugin.core.http.Request
    uri: https://dev123.service-now.com/api/now/table/incident
    options:
      basicAuthUser: annabelle.coger
      basicAuthPassword: mypass
  - id: service
    type: io.kestra.plugin.servicenow.Get
    username: annabelle.coger
    password: mypass
    domain: dev123
    table: incident
```

### Environment Information

- Kestra Version: 0.22-rc1
- Plugin version: 0.22-rc1
- Operating System (OS / Docker / Kubernetes): Docker
